#!/bin/bash

PROJECT="src"

# تعریف آرایه‌ای از مسیرها
dirs=(
    "app/(public)/category"
    "app/(public)/product"
    "app/(public)/collections"
    "app/(public)/brand"
    "app/(public)/blog"
    "app/(public)/search"
    "app/(public)/faq"
    "app/(public)/contact"
    "app/(public)/about"
    "app/(auth)/login"
    "app/(auth)/register"
    "app/(auth)/callback"
    "app/(dashboard)/products"
    "app/(dashboard)/categories"
    "app/(dashboard)/orders"
    "app/(dashboard)/customers"
    "app/(dashboard)/discounts"
    "app/(dashboard)/cms"
    "app/(dashboard)/reports"
    "app/(dashboard)/settings"
    "app/api/webhooks"
#    "features/auth"
#    "features/cart"
#    "features/checkout"
#    "features/product"
#    "features/order"
#    "features/wishlist"
#    "features/profile"
#    "features/search"
#    "features/notification"
#    "features/admin/products"
#    "features/admin/categories"
#    "entities/product"
#    "entities/order"
#    "entities/user"
#    "entities/category"
#    "entities/brand"
#    "entities/review"
#    "shared/ui"
#    "shared/components"
#    "shared/hooks"
#    "shared/providers"
#    "shared/api"
#    "shared/services"
#    "shared/lib"
#    "shared/utils"
#    "shared/constants"
#    "shared/types"
#    "shared/schemas"
#    "shared/validations"
#    "shared/configs"
#    "shared/stores"
#    "shared/assets/icons"
#    "shared/assets/images"
#    "shared/i18n"
)

for dir in "${dirs[@]}"; do
    mkdir -p "$PROJECT/$dir"
done

# فایل‌ها
files=(
    "app/(public)/layout.tsx"
    "app/(public)/page.tsx"
    "app/(dashboard)/layout.tsx"
    "app/(dashboard)/page.tsx"
    "app/globals.css"
    "app/layout.tsx"
    "app/loading.tsx"
    "app/error.tsx"
    "app/not-found.tsx"
    "middleware.ts"
    "next.config.mjs"
    "tailwind.config.ts"
    "tsconfig.json"
    "eslint.config.mjs"
    "prettier.config.mjs"
    ".env.example"
    "package.json"
    "README.md"
)

for file in "${files[@]}"; do
    touch "$PROJECT/$file"
done

echo "✅ ساختار پروژه در $PROJECT ساخته شد."
